CABINETS = [
    {"place_type": "cabinet", "cabinet": "10"},
    {"place_type": "cabinet", "cabinet": "14"},
    {"place_type": "cabinet", "cabinet": "20"},
    {"place_type": "cabinet", "cabinet": "25"},
    {"place_type": "cabinet", "cabinet": "26"},
    {"place_type": "cabinet", "cabinet": "30"},
    {"place_type": "cabinet", "cabinet": "31"},
    {"place_type": "cabinet", "cabinet": "34"},
    {"place_type": "cabinet", "cabinet": "35"},
    {"place_type": "cabinet", "cabinet": "37"},
    {"place_type": "cabinet", "cabinet": "39"},
    {"place_type": "cabinet", "cabinet": "41"},
    {"place_type": "cabinet", "cabinet": "C3"},
]