"""initial migration

Revision ID: 052d1ddcbbd8
Revises: 
Create Date: 2026-02-20 15:04:09.053822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052d1ddcbbd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('name_uk', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('day_id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_uk'),
    schema='schedule'
    )
    op.create_table('lecturers',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('lecturer_id'),
    schema='schedule'
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('lesson_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    schema='schedule'
    )
    op.create_table('slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('slot_id'),
    sa.UniqueConstraint('time_start', 'time_end'),
    schema='schedule'
    )
    op.create_table('specialties',
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('specialty_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    schema='schedule'
    )
    op.create_table('venues',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('venue_id'),
    schema='schedule'
    )
    op.create_table('student_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('course BETWEEN 1 AND 4', name='check_course_range'),
    sa.ForeignKeyConstraint(['specialty_id'], ['schedule.specialties.specialty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('specialty_id', 'course', 'group_number'),
    schema='schedule'
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('week_id IN (1, 2)', name='check_week_id_range'),
    sa.ForeignKeyConstraint(['day_id'], ['schedule.days.day_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['schedule.student_groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['schedule.lecturers.lecturer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['schedule.lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['schedule.slots.slot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['schedule.venues.venue_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('schedule_id'),
    schema='schedule'
    )
    with op.batch_alter_table('schedules', schema='schedule') as batch_op:
        batch_op.create_index('idx_group_week', ['group_id', 'week_id'], unique=False)
        batch_op.create_index('idx_lecturer_week', ['lecturer_id', 'week_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema='schedule') as batch_op:
        batch_op.drop_index('idx_lecturer_week')
        batch_op.drop_index('idx_group_week')

    op.drop_table('schedules', schema='schedule')
    op.drop_table('student_groups', schema='schedule')
    op.drop_table('venues', schema='schedule')
    op.drop_table('specialties', schema='schedule')
    op.drop_table('slots', schema='schedule')
    op.drop_table('lessons', schema='schedule')
    op.drop_table('lecturers', schema='schedule')
    op.drop_table('days', schema='schedule')
    # ### end Alembic commands ###
