"""initial migration

Revision ID: 84490eae1a04
Revises: 
Create Date: 2026-02-20 01:37:09.013859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84490eae1a04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('name_uk', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('day_id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_uk'),
    schema='schedule'
    )
    op.create_table('lecturers',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('lecturer_id'),
    schema='schedule'
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('lesson_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    schema='schedule'
    )
    op.create_table('slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('slot_id'),
    schema='schedule'
    )
    op.create_table('specialties',
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('specialty_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    schema='schedule'
    )
    op.create_table('venues',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('venue_id'),
    schema='schedule'
    )
    op.create_table('student_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('course BETWEEN 1 AND 4', name='check_course_range'),
    sa.ForeignKeyConstraint(['specialty_id'], ['schedule.specialties.specialty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('specialty_id', 'course', 'group_number'),
    schema='schedule'
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('week_id IN (1, 2)', name='check_week_id_range'),
    sa.ForeignKeyConstraint(['day_id'], ['schedule.days.day_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['schedule.student_groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['schedule.lecturers.lecturer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['schedule.lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['schedule.slots.slot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['schedule.venues.venue_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('schedule_id'),
    schema='schedule'
    )
    with op.batch_alter_table('schedules', schema='schedule') as batch_op:
        batch_op.create_index('idx_group_week', ['group_id', 'week_id'], unique=False)
        batch_op.create_index('idx_lecturer_week', ['lecturer_id', 'week_id'], unique=False)
    op.drop_table('overall_schedule')
    op.drop_table('lecturers')
    op.drop_table('times')
    op.drop_table('group_presence')
    op.drop_table('student_groups')
    op.drop_table('days')
    op.drop_table('places')
    op.drop_table('lessons')
    op.drop_table('specialties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('day_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('day_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('day_id', name=op.f('days_pkey'))
    )
    op.create_table('student_groups',
    sa.Column('group_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('specialty_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('course >= 1 AND course <= 4', name=op.f('check_course_range')),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.specialty_id'], name=op.f('student_groups_specialty_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', name=op.f('student_groups_pkey')),
    sa.UniqueConstraint('specialty_id', 'course', 'group_number', name=op.f('student_groups_specialty_id_course_group_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('group_presence',
    sa.Column('presence_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('week_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint('week_id = ANY (ARRAY[1, 2])', name=op.f('check_week_id_range')),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.group_id'], name=op.f('group_presence_group_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('presence_id', name=op.f('group_presence_pkey'))
    )
    op.create_table('times',
    sa.Column('time_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('time_start', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('time_end', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('time_id', name=op.f('times_pkey'))
    )
    op.create_table('lecturers',
    sa.Column('lecturer_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('lecturer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('lecturer_id', name=op.f('lecturers_pkey')),
    sa.UniqueConstraint('lecturer_name', name=op.f('lecturers_lecturer_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('overall_schedule',
    sa.Column('schedule_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('time_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lecturer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('week_id = ANY (ARRAY[1, 2])', name=op.f('check_week_id_range')),
    sa.ForeignKeyConstraint(['day_id'], ['days.day_id'], name=op.f('overall_schedule_day_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.group_id'], name=op.f('overall_schedule_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.lecturer_id'], name=op.f('overall_schedule_lecturer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], name=op.f('overall_schedule_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], name=op.f('overall_schedule_place_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_id'], ['times.time_id'], name=op.f('overall_schedule_time_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('overall_schedule_pkey'))
    )
    op.create_table('specialties',
    sa.Column('specialty_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('specialty_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('specialty_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('specialty_id', name=op.f('specialties_pkey')),
    sa.UniqueConstraint('specialty_code', name=op.f('specialties_specialty_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('specialty_name', name=op.f('specialties_specialty_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('lesson_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('lesson_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('lesson_id', name=op.f('lessons_pkey')),
    sa.UniqueConstraint('lesson_code', name=op.f('lessons_lesson_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('lesson_name', name=op.f('lessons_lesson_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('places',
    sa.Column('place_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('cabinet', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('cabinet IS NOT NULL AND url IS NULL OR cabinet IS NULL AND url IS NOT NULL', name=op.f('cabinet_or_url_xor')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], name=op.f('places_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', name=op.f('places_pkey'))
    )
    with op.batch_alter_table('schedules', schema='schedule') as batch_op:
        batch_op.drop_index('idx_lecturer_week')
        batch_op.drop_index('idx_group_week')

    op.drop_table('schedules', schema='schedule')
    op.drop_table('student_groups', schema='schedule')
    op.drop_table('venues', schema='schedule')
    op.drop_table('specialties', schema='schedule')
    op.drop_table('slots', schema='schedule')
    op.drop_table('lessons', schema='schedule')
    op.drop_table('lecturers', schema='schedule')
    op.drop_table('days', schema='schedule')
    # ### end Alembic commands ###
